#!/usr/bin/env php
# file was generated by <?=basename(__FILE__)?>; do not edit!
language: c

addons:
 apt:
  packages:
   - php-cli
   - php-pear

dist: xenial

cache:
 apt: true
 directories:
  - $HOME/cache

env:
<?php

$gen = include "./travis/pecl/gen-matrix.php";
$cur = "7.4";
$env = $gen([
	// most useful for all additional versions except current
	"PHP"                   => ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "master"],
	"enable_debug",
	"enable_maintainer_zts"
]);
foreach ($env as $grp) {
	foreach ($grp as $e) {
		printf(" - %s\n", $e);
	}
}
?>

matrix:
 fast_finish: true
 allow_failures:
<?php
$allow_failures = array_merge( ... array_map(function($a) {
	return preg_grep('/^PHP=(master|8.0) /', $a);
}, $env));
foreach ($allow_failures as $e) {
	printf("  - env: %s\n", $e);
}
?>

before_script:
 - make -f travis/pecl/Makefile php
 - make -f travis/pecl/Makefile ext PECL=realpath_turbo

script:
 - make -f travis/pecl/Makefile test
